
language: objective-c  #1
osx_image: xcode8.1
script: 
        - xcodebuild -workspace Example/EJURouterSDK.xcworkspace -scheme EJURouterSDK-Example build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO 
